version: "3"
services:
  node:
    build:
      context: ./.Docker/node
      dockerfile: Dockerfile
    container_name: node
    user: 1000:1000
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./node/:/home/node/app
    ports:
      - "9001:80"
      - "9002:8000"
      - "9003:9000"
    command: tail -f /dev/null
